name: Auto Release This Project
run-name: Auto release
on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create artifacts
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.9'
    - name: Start Building
      run: |
        git clone --branch=master https://github.com/asAsadwS/FastestBilibiliDownloader.git biliDL
        cd biliDL
        go build -o biliDL-linux-dyn cmd/start-concurrent-engine.go
        CGO_ENABLED=0 go build --ldflags "-extldflags '-static'" -o biliDL-linux-static cmd/start-concurrent-engine.go
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o biliDL-windows cmd/start-concurrent-engine.go
    - name: Upload Lniux static program
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.BILIDL_TOKEN }}
        file: biliDL/biliDL-linux-static
        tags: ${{ github.sha }}
    - name: Upload Lniux program
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.BILIDL_TOKEN }}
        file: biliDL/biliDL-linux-dyn
        tags: ${{ github.sha }}
    - name: Upload Windows
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.BILIDL_TOKEN }}
        file: biliDL/biliDL-windows
        tags: ${{ github.sha }}


